version: '3.4'

services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

services:
flaskapp:
    image: flaskapp
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    build: .
    env_file: .env.prod
    depends_on:
    - db
    ports:
    - 5000:5000

db:
    image: postgres:latest
    networks:
    - default
    ports:
    - 5432:5432
    restart: always
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    env_file: .env.prod

volumes:
postgres_data:
      