version: '3.4'

services:
  flaskapp:
    build: ./flask
    container_name: flask
    restart: always
    env_file: .env.dev
    depends_on:
      - db
    expose:
      - 8080
    ports:
      - 5000:5000
  
  db:
    image: postgres:latest
    restart: always
    env_file: .env.dev
    networks:
      - default
    ports:
      - 5432:5432
    
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

volumes:
  postgres_data:
